
##teamcity[testStarted name='testAssert (__main__.TestTeamcityMessages)']

##teamcity[testFailed message='Failure' name='testAssert (__main__.TestTeamcityMessages)' details='Traceback (most recent call last):|n  File "unittest.py", line 260, in run|n    testMethod()|n  File "test-unittest.py", line 15, in testAssert|n    self.assert_(False)|n  File "unittest.py", line 309, in failUnless|n    if not expr: raise self.failureException, msg|nAssertionError|n']

##teamcity[testFinished name='testAssert (__main__.TestTeamcityMessages)']

##teamcity[testStarted name='testAssertEqual (__main__.TestTeamcityMessages)']

##teamcity[testFailed message='Failure' name='testAssertEqual (__main__.TestTeamcityMessages)' details='Traceback (most recent call last):|n  File "unittest.py", line 260, in run|n    testMethod()|n  File "test-unittest.py", line 9, in testAssertEqual|n    self.assertEqual("1", "2")|n  File "unittest.py", line 334, in failUnlessEqual|n    (msg or |'%r != %r|' % (first, second))|nAssertionError: |'1|' != |'2|'|n']

##teamcity[testFinished name='testAssertEqual (__main__.TestTeamcityMessages)']

##teamcity[testStarted name='testAssertEqualMsg (__main__.TestTeamcityMessages)']

##teamcity[testFailed message='Failure' name='testAssertEqualMsg (__main__.TestTeamcityMessages)' details='Traceback (most recent call last):|n  File "unittest.py", line 260, in run|n    testMethod()|n  File "test-unittest.py", line 12, in testAssertEqualMsg|n    self.assertEqual("1", "2", "message")|n  File "unittest.py", line 334, in failUnlessEqual|n    (msg or |'%r != %r|' % (first, second))|nAssertionError: message|n']

##teamcity[testFinished name='testAssertEqualMsg (__main__.TestTeamcityMessages)']

##teamcity[testStarted name='testException (__main__.TestTeamcityMessages)']

##teamcity[testFailed message='Error' name='testException (__main__.TestTeamcityMessages)' details='Traceback (most recent call last):|n  File "unittest.py", line 260, in run|n    testMethod()|n  File "test-unittest.py", line 21, in testException|n    raise Exception("some exception")|nException: some exception|n']

##teamcity[testFinished name='testException (__main__.TestTeamcityMessages)']

##teamcity[testStarted name='testFail (__main__.TestTeamcityMessages)']

##teamcity[testFailed message='Failure' name='testFail (__main__.TestTeamcityMessages)' details='Traceback (most recent call last):|n  File "unittest.py", line 260, in run|n    testMethod()|n  File "test-unittest.py", line 18, in testFail|n    self.fail("failed")|n  File "unittest.py", line 301, in fail|n    raise self.failureException, msg|nAssertionError: failed|n']

##teamcity[testFinished name='testFail (__main__.TestTeamcityMessages)']

##teamcity[testStarted name='testPass (__main__.TestTeamcityMessages)']
ok

##teamcity[testFinished name='testPass (__main__.TestTeamcityMessages)']
